services:
  pwneu.gateway:
    image: nginx:latest
    container_name: pwneu.gateway
    depends_on:
      - pwneu.mq
      - pwneu.identity
      - pwneu.play
      - pwneu.chat
    ports:
      - "37100:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./conf/robots.txt:/etc/nginx/robots.txt:ro
    networks:
      - pwneu

  pwneu.identity:
    container_name: pwneu.identity
    depends_on:
      - pwneu.identity.db
      - pwneu.cache
      - pwneu.mq
    build:
      context: .
      dockerfile: src/Pwneu.Identity/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Postgres=${IDENTITY_CONNECTION}
      - MessageBroker__Username=${RABBITMQ_DEFAULT_USER}
      - MessageBroker__Password=${RABBITMQ_DEFAULT_PASS}
      - AppOptions__InitialAdminPassword=${ADMIN_PASSWORD}
      - AppOptions__ValidEmailDomain=${VALID_EMAIL_DOMAIN}
      - AppOptions__TurnstileSecretKey=${TURNSTILE_SECRET_KEY}
      - AppOptions__IsTurnstileEnabled=${IS_TURNSTILE_ENABLED}
      - AppOptions__FrontendUrl=${RESET_PASSWORD_URL}
      - JwtOptions__Issuer=${JWT_ISSUER}
      - JwtOptions__Audience=${JWT_AUDIENCE}
      - JwtOptions__SigningKey=${JWT_SIGNING_KEY}
    networks:
      - pwneu

  pwneu.identity.db:
    image: postgres:latest
    container_name: pwneu.identity.db
    environment:
      - POSTGRES_DB=${IDENTITY_DB}
      - POSTGRES_USER=${IDENTITY_USER}
      - POSTGRES_PASSWORD=${IDENTITY_PASSWORD}
    volumes:
      - ./.containers/identity.db:/var/lib/postgresql/data
    networks:
      - pwneu

  pwneu.play:
    container_name: pwneu.play
    depends_on:
      - pwneu.play.db
      - pwneu.cache
      - pwneu.mq
    build:
      context: .
      dockerfile: src/Pwneu.Play/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Postgres=${PLAY_CONNECTION}
      - MessageBroker__Username=${RABBITMQ_DEFAULT_USER}
      - MessageBroker__Password=${RABBITMQ_DEFAULT_PASS}
      - JwtOptions__Issuer=${JWT_ISSUER}
      - JwtOptions__Audience=${JWT_AUDIENCE}
      - JwtOptions__SigningKey=${JWT_SIGNING_KEY}
    networks:
      - pwneu

  pwneu.play.db:
    image: postgres:latest
    container_name: pwneu.play.db
    environment:
      - POSTGRES_DB=${PLAY_DB}
      - POSTGRES_USER=${PLAY_USER}
      - POSTGRES_PASSWORD=${PLAY_PASSWORD}
    volumes:
      - ./.containers/play.db:/var/lib/postgresql/data
    networks:
      - pwneu

  pwneu.chat:
    container_name: pwneu.chat
    depends_on:
      - pwneu.cache
      - pwneu.mq
    build:
      context: .
      dockerfile: src/Pwneu.Chat/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - MessageBroker__Username=${RABBITMQ_DEFAULT_USER}
      - MessageBroker__Password=${RABBITMQ_DEFAULT_PASS}
      - ChatOptions__ConversationIsEnabled=${CHAT_CONVERSATION_IS_ENABLED}
      - ChatOptions__MaxConversationsPerDay=${CHAT_MAX_CONVERSATIONS_PER_DAY}
      - ChatOptions__OpenAiApiKey=${CHAT_OPENAI_API_KEY}
      - JwtOptions__Issuer=${JWT_ISSUER}
      - JwtOptions__Audience=${JWT_AUDIENCE}
      - JwtOptions__SigningKey=${JWT_SIGNING_KEY}
    volumes:
      - ./.containers/chat.db/:/db
    networks:
      - pwneu

  pwneu.smtp:
    container_name: pwneu.smtp
    depends_on:
      - pwneu.identity
      - pwneu.play
    build:
      context: .
      dockerfile: src/Pwneu.Smtp/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - MessageBroker__Username=${RABBITMQ_DEFAULT_USER}
      - MessageBroker__Password=${RABBITMQ_DEFAULT_PASS}
      - SmtpOptions__SenderAddress=${SMTP_SENDER_ADDRESS}
      - SmtpOptions__SenderPassword=${SMTP_SENDER_PASSWORD}
      - SmtpOptions__NotifyLoginIsEnabled=${SMTP_NOTIFY_LOGIN_IS_ENABLED}
      - SmtpOptions__SendEmailConfirmationIsEnabled=${SMTP_SEND_EMAIL_CONFIRMATION_IS_ENABLED}
      - SmtpOptions__SendPasswordResetTokenIsEnabled=${SMTP_SEND_PASSWORD_RESET_TOKEN_IS_ENABLED}
      - SmtpOptions__VerifyEmailUrl=${SMTP_VERIFY_EMAIL_URL}
      - SmtpOptions__ResetPasswordUrl=${SMTP_RESET_PASSWORD_URL}
    networks:
      - pwneu

  pwneu.cache:
    image: redis:latest
    container_name: pwneu.cache
    networks:
      - pwneu

  pwneu.mq:
    image: rabbitmq:management
    container_name: pwneu.mq
    volumes:
      - ./.containers/queue/data/:/var/lib/rabbitmq
      - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - pwneu

  pwneu.monitoring:
    image: prom/prometheus:latest
    container_name: pwneu.monitoring
    depends_on:
      - pwneu.identity
      - pwneu.play
      - pwneu.chat
      - pwneu.smtp
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./.containers/prometheus:/prometheus
    networks:
      - pwneu

  pwneu.dashboard:
    image: grafana/grafana-oss:latest
    container_name: pwneu.dashboard
    depends_on:
      - pwneu.monitoring
    ports:
      - "37004:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./conf/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./.containers/grafana:/var/lib/grafana
    networks:
      - pwneu

networks:
  pwneu: