services:
  pwneu.identity:
    ports:
      - "37200:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  pwneu.identity.db:
    ports:
      - "37202:5432"

  pwneu.play:
    ports:
      - "37300:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  pwneu.play.db:
    ports:
      - "37302:5432"

  pwneu.chat:
    ports:
      - "37400:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  pwneu.smtp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  pwneu.cache:
    ports:
      - "6379:6379"

  pwneu.mq:
    ports:
      - "5672:5672"
      - "15672:15672"