services:
  pwneu.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  pwneu.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  pwneu.play:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  pwneu.chat:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  pwneu.smtp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
